name: "Pooled CNN"

on:
  push:
    branches: [main]

jobs:
  

  cnn_pooled:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Python 3.10.1
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip" # caching pip dependencies
          cache-dependency-path: "**/requirements.txt"
      - run: pip install -r requirements.txt
      - run: python ParrotSourPreProcessor.py
      - run: python PSCNNPooled.py

      - uses: actions/upload-artifact@v3
        name: Upload RF Model
        with:
          name: best-cnn-model
          path: ps_cnn_model_2.h5

  