name: "Pooled CNN"

on:
  push:
    branches: [main]

jobs:
  

  cnn_pooled:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Preprocess data
        run: python ParrotSourPreProcessor.py
      - name: Run CNN script
        run: python PSCNNPooled.py
      - name: Upload RF Model
        uses: actions/upload-artifact@v2
        with:
          name: cnn-model
          path: ps_cnn_model_2.h5
  
  