name: "ParrotSourML Jobs"

on:
  push:
    branches: [main]

jobs:
  runners:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        command: ["PSRandomForestRunner.py", "PSSVMRunner.py"]

    steps:
      - uses: actions/checkout@v3
      - name: Use Python 3.10.1
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip" # caching pip dependencies
          cache-dependency-path: "**/requirements.txt"
      - run: pip install -r requirements.txt

      - run: python ParrotSourPreProcessor.py

      - run: python ${{ matrix.command }}

  rf_pooled:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Python 3.10.1
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip" # caching pip dependencies
          cache-dependency-path: "**/requirements.txt"
      - run: pip install -r requirements.txt
      - run: python ParrotSourPreProcessor.py
      - run: python PSRandomForestPooled.py

      - uses: actions/upload-artifact@v3
        name: Upload RF Model
        with:
          name: best-rf-model
          path: PSRandomForestSaved.jbl

  rf_predict:
    runs-on: ubuntu-latest
    needs: [rf_pooled]
    steps:
      - uses: actions/checkout@v3
      - name: Use Python 3.10.1
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip" # caching pip dependencies
          cache-dependency-path: "**/requirements.txt"
      - run: pip install -r requirements.txt

      - uses: actions/download-artifact@v2
        name: Download saved RF model
        with:
          name: best-rf-model

      - run: python PSRandomForestTest.py

  svm_pooled:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Python 3.10.1
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip" # caching pip dependencies
          cache-dependency-path: "**/requirements.txt"
      - run: pip install -r requirements.txt

      - run: python ParrotSourPreProcessor.py

      # note: should limit to 10 as the time required increases exponentially with wider ranges
      - run: python PSSVMPooled.py 12 17

      - uses: actions/upload-artifact@v3
        name: Upload SVM Model
        with:
          name: best-svm-model
          path: PSSVMSaved.jbl

  svm_predict:
    runs-on: ubuntu-latest
    needs: [svm_pooled]
    steps:
      - uses: actions/checkout@v3
      - name: Use Python 3.10.1
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip" # caching pip dependencies
          cache-dependency-path: "**/requirements.txt"
      - run: pip install -r requirements.txt

      - uses: actions/download-artifact@v2
        name: Download saved SVM model
        with:
          name: best-svm-model

      - run: python PSSVMTest.py

  cnn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Python 3.10.1
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip" # caching pip dependencies
          cache-dependency-path: "**/requirements.txt"
      - run: pip install -r requirements.txt

      - run: python ParrotSourPreProcessor.py

      - run: python PSCNN.py

      - uses: actions/upload-artifact@v3
        name: Upload CNN Model
        with:
          name: cnn-model
          path: ps_cnn_model.h5

  cnn_predict:
    runs-on: self-hosted
    needs: [cnn]
    steps:
      - uses: actions/checkout@v3
      - name: Use Python 3.10.1
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip" # caching pip dependencies
          cache-dependency-path: "**/requirements.txt"
      - run: pip install -r requirements.txt

      - uses: actions/download-artifact@v2
        name: Download saved CNN model
        with:
          name: cnn-model

      - name: Run CNN Prediction
        run: python PSCNNTest.py

  cnn_large:
    runs-on: ubuntu-latest
    needs: [cnn]
    steps:
      - uses: actions/checkout@v3
      - name: Use Python 3.10.1
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip" # caching pip dependencies
          cache-dependency-path: "**/requirements.txt"
      - run: pip install -r requirements.txt

      - run: python ParrotSourPreProcessor.py data25000.json

      - run: python PSCNN.py

      - uses: actions/upload-artifact@v3
        name: Upload Large CNN Model
        with:
          name: cnn-large-model
          path: ps_cnn_model.h5

  cnn_large_predict:
    runs-on: ubuntu-latest
    needs: [cnn_large]
    steps:
      - uses: actions/checkout@v3
      - name: Use Python 3.10.1
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip" # caching pip dependencies
          cache-dependency-path: "**/requirements.txt"
      - run: pip install -r requirements.txt

      - uses: actions/download-artifact@v2
        name: Download saved 25k CNN model
        with:
          name: cnn-large-model

      - run: python PSCNNTest.py
