# This workflow will do a clean install of node dependencies, cache/restore them, and build using node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Random Forest

on:
  push:
    branches: [dev]
  pull_request:
    branches: [main]

jobs:
  random_forest:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        py-version: [3.10.1]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Python ${{ matrix.py-version }}
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip" # caching pip dependencies
      - run: pip install -r requirements.txt
      - run: python ./ParrotSourPreprocessor.py
      - run: python ./PSRandomForestRunner.py
